routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Frontend\IndexController@index');
Route::post('/postSubscribe', 'Frontend\IndexController@subscribe');
Route::get('{post}-{name}', 'Frontend\IndexController@show');
Route::get('/category/{id}-{name}', 'Frontend\IndexController@category');
Route::post('/commentPost', 'Frontend\IndexController@commentPost');
Route::get('/search', 'Frontend\IndexController@search');
Route::get('/lang/{lang}', 'LangController@index');

Auth::routes();

Route::get('/home', 'Frontend\IndexController@index')->name('home');
//set status routes
Route::post('set-statususer', 'Backend\UsersController@setStatus')->name('setStatusUser');
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm');
Route::post('admin/login', 'Auth\AdminLoginController@login')->name('admin.login');

Route::group(['middleware' => 'banned','auth'], function(){
    Route::get('/user', 'Frontend\UserController@index');
});

Route::group(['prefix' => 'admin','middleware' => 'assign.guard:admin,admin/login'],function(){
    Route::get('/home', 'Backend\AdminController@index');
    Route::get('/getSubCategory/{categoryId}', 'Backend\PostsController@getSubCategoryById');
    Route::resources([
        'user' => 'Backend\UsersController',
        'category' => 'Backend\CategoriesController',
        'main_category' => 'Backend\MainCategoryController',
        'tag' => 'Backend\TagsController',
        'socials' => 'Backend\SocialsController',
        'contact' => 'Backend\ContactController',
        'about' => 'Backend\AboutController',
        'post' => 'Backend\PostsController',
        'comment' => 'Backend\CommentsController',
    ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'image', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Backend/UsersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'DESC')->get();
        $settings = $this->getSettingsForTable();
        return view('admin.pages.user.users', compact('users', 'settings'));
    }

    public function setStatus(Request $request)
    {
        if ($request->ajax())
        {
            DB::table($request->table)->where('id',$request->id)->update(['status' => $request->status]);
            $resultMessage = ($request->status) ? "İstifadəçi aktiv olundu" : "İstifadəçi deaktiv olundu";
            return response($resultMessage,200);

        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $setting = $this->getSettingsForForm();
        $setting['title'] = 'Düzəliş et';
        return view('admin.pages.user.edit',compact('user','setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->save();
        $request->session()->flash(str_slug('Düzəliş et','-'),'Düzəliş edildi');
        return back();
    }

        /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,User $user)
    {
        $user->delete();
        $request->session()->flash(str_slug('İstifadəçilər','-'),'İstifadəçi silindi');
        return back();
    }

    /**
     *  Return setting array for table component
     * @return array
     */
    private function getSettingsForTable()
    {
        return  [
            'title' => 'İstifadəçilər',
            'table' => 'users',
            'createButton' => [
                'text' => "İstifadəçi",
                'url' => route('user.index')
            ],
            'columns' => [
                [
                    'label' => 'ID',
                ],
                [
                    'label' => 'Ad',
                ],
                [
                    'label' => 'Email'
                ],
                [
                    'label' => 'Balans'
                ],
                [
                    'label' => 'Status',
                ]
            ],
        ];
    }

    /**
     * Return setting array for form component
     * @return array
     */
    private  function  getSettingsForForm()
    {
        return [
            'title' => 'Əlavə et',
            'flashSessionKey' => 'user',
            'flashSessionValue' => 'Əlavə edildi',
            'backButton' => [
                'text' => "Əvvələ",
                'url' => route('user.index')
            ]
        ];
    }
}

app/Http/Controllers/Frontend/UserController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MetaTag;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        MetaTag::set('title', 'Müştəri Paneli');
        return view('frontend.pages.profile');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/user/edit.blade.php
@component('admin.components.form',$setting)
    {{-- Component content--}}
    <form id="form_validation" action="{{route('user.update',['user' => $user->id])}}" method="post">
        {{method_field('PUT')}}
        @csrf
        <div class="row clearfix">
            <div class="col-sm-12">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input name="name" type="text" required class="form-control" value="{{$user->name}}">
                        <label class="form-label">Ad</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input name="email" type="email" required class="form-control" value="{{$user->email}}">
                        <label class="form-label">Email</label>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group form-float">
                    <div class="form-line">
                        <input name="password" type="password" required class="form-control" placeholder="Password">
                        <label class="form-label">Şifrə</label>
                    </div>
                </div>
            </div>
            {{--<div class="col-sm-12">--}}
                {{--<div class="form-group form-float">--}}
                    {{--<div class="form-line">--}}
                        {{--<input name="password_confirmation" type="text" required class="form-control" placeholder="Confirm passswprd">--}}
                        {{--<label class="form-label">Təkrar şifrə</label>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
            <div class="col-sm-12">
                <div class="demo-switch">
                    <button type="submit" class="btn btn-success waves-effect right">Yenilə</button>
                </div>
            </div>
        </div>
    </form>

    <script>
        $('.datepicker').bootstrapMaterialDatePicker({
            format: 'dddd DD MMMM YYYY',
            clearButton: true,
            weekStart: 1,
            time: false
        });
    </script>
@endcomponent

resources/views/admin/pages/user/users.blade.php
@component('admin.components.table',$settings)
    {{-- Component content--}}
    @foreach($users as $user)

        <tr>
            <td>{{$user->id}}</td>
            <td>{{$user->name}}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->balance }}</td>
            <td>
                <div class="switch">
                    <label><input class="statusCheckBoxUser" data-row="{{$user->id}}" type="checkbox" {{($user->status) ? 'checked' : ""}}><span class="lever"></span></label>
                </div>
            </td>
            <td>
                <a class="btn bg-blue btn-circle waves-effect waves-circle waves-float" style="float: left;margin-right: 10px;" href="{{route('user.edit',['user' => $user->id])}}"><i class="material-icons">edit</i></a>
                <form action="{{route('user.destroy',['user' => $user->id])}}" method="post">
                    {{ method_field('delete') }}
                    @csrf
                    <button type="submit" class="btn bg-red btn-circle waves-effect waves-circle waves-float">
                        <i class="material-icons">delete</i>
                    </button>
                </form>
            </td>
        </tr>

    @endforeach
@endcomponent